import type { Metadata } from "next";
import { Inter, Gowun_Dodum, Anek_Bangla } from "next/font/google";
import "./globals.css";

const inter = Inter({ subsets: ["latin"] });

export const yomogi_init = Anek_Bangla({
  weight: '400',
  subsets: ["latin"],
  display: "swap",
  variable: "--font-yomogi",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${inter.className} ${yomogi_init.variable}`}>{children}</body>
    </html>
  );
}
